# Generated by Django 4.2.3 on 2023-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone_locker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
