# Generated by Django 4.2.3 on 2023-07-26 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zone_locker', '0002_alter_zone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='lock_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
